name: Merge to Main

on:
  push:
    branches:
    - main

env:
  CGO_ENABLED: "0"

jobs:
# build
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd
          ls -la
          go mod vendor
          make build

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
      - run: |
          jf rt ping
          