name: Pull Request

on:
  pull_request:
    branches:
    - main

env:
  CGO_ENABLED: "0"

jobs:
# tests and units
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: go test ./...
